### ISSUE TITLE
Error: Key Validation Error: it cannot contain commas.

### ISSUE THREAD

**Issue by PerchunPak** [ItsDrike/setup-poetry#2]
The problem is that the tool without encoding `install-args`, adding it to cache key. So `install-args: --only main,ci` will always fail.

[Here is the error in my CI](https://github.com/PerchunPak/pinger-bot/actions/runs/4513018015/jobs/7947325054#step:3:153).

**Comment by ItsDrike** [comment]
Hmm, interesting, I suppose this could be handled with just base64 encode. B64 contains these chars: `ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/`, which should hopefully all be usable as cache keys.

**Comment by ItsDrike** [comment]
Resolved in [v1.1.3](https://github.com/ItsDrike/setup-poetry/releases/tag/v1.1.3).

(The v1 and v1.1 tags were updated to match this revision, so no need for any changes in your workflow if you're just using `@v1`, however if you're using `ItsDrike/setup-poetry@v1.1.2`, you will need to bump it up to 1.1.3)
