### ISSUE TITLE
Possible stuck of deleted dependencies

### ISSUE THREAD

**Issue by PerchunPak** [ItsDrike/setup-poetry#3]
If someone, will firstly add to dependencies some library, create cache entries and then delete the dependency - it will stay in the cache, and poetry will not remove it because you do not provide the `--sync` argument to `poetry install` (which removes all untracked dependencies in venv).

---

So for reproduce:

1. Add `foo` to dependencies.
2. Run CI once.
3. Delete `foo`.

As cache will be restored from `restore-key`, the `foo` will stay and `poetry` will not manage it because it isn't in `poetry.lock`.

**Comment by ItsDrike** [comment]
Good catch, would just adding the `--sync` argument fix this?

**Comment by PerchunPak** [comment]
I think yes

**Comment by ItsDrike** [comment]
Fixed in c9b6ed0ec675272df0fee47860da0efbbbea321c, `--sync` argument is now added by default
