### ISSUE TITLE
`v1.1.3` doesn't work because sha256sum: command not found

### ISSUE THREAD

**Issue by PerchunPak** [ItsDrike/setup-poetry#5]
See https://github.com/py-mine/mcstatus/actions/runs/4761861983/jobs/8463495730?pr=522#step:3:72.

**Comment by ItsDrike** [comment]
My bad, forgot macs don't have `sha256sum` command installed by default, switched to using `openssl sha256`, which should work everywhere. Released [v1.1.4](https://github.com/ItsDrike/setup-poetry/releases/tag/v1.1.4)
